kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: sealed-secrets

bases:
  - ../../base

patchesJson6902:
  - path: patch-sealed-secrets.yaml
    target:
      group: apps
      kind: Deployment
      name: sealed-secrets-controller
      version: v1
      namespace: kube-system
