apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rfe-automation
  namespace: rfe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rfe-automation
subjects:
  - kind: ServiceAccount
    name: rfe-automation
    namespace: rfe
