---
- name: Validate Composer Sources file Exists
  local_action: stat path="{{ composer_sources_path }}"
  become: false
  register: sources_file_exists
  failed_when: not sources_file_exists.stat.exists
  connection: local

- name: Load Composer Source File
  ansible.builtin.set_fact:
    composer_sources: "{{ lookup('file', composer_sources_path) | from_yaml }}"

- name: Add Composer Source Files
  block:
    - name: Create Sources Temp Directory
      ansible.builtin.file:
        state: directory
        path: "{{ composer_sources_tmp_dir }}"

    - name: Process Composer Sources
      ansible.builtin.include_tasks: add-composer-source.yaml
      loop: "{{ composer_sources }}"
      loop_control:
        loop_var: composer_source
  when: composer_sources | length > 0
  always:
    - name: Remove Sources Temp Directory
      ansible.builtin.file:
        state: absent
        path: "{{ composer_sources_tmp_dir }}"
