apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd
  namespace: httpd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
