apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "nexus.setupJobName" . }}
  namespace: {{ template "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
      - create
