apiVersion: v1
kind: ConfigMap
metadata:
  name: "image-builder-vm-composer"
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
data:
  sources.yaml: |
    {{- tpl (toYaml .Values.imageBuilderVM.composer.sources) $ | nindent 4 }}